### ISSUE TITLE
When I press the "Encrypt" button, it is not encrypted.

### ISSUE THREAD

**Issue by jstapletton** [TheNewAttacker64/File-Unpumper#1]
It says "Copy the content of loader.txt and paste it in pastebin then copy the raw URL and paste it into Builder Area". I am doing what is said.

I select everything written in the loader.txt file with CTRL+A, copy and paste it into pastebin. Then I press the "raw" tab, copy the URL and paste it into the "Builder Area". So what should I do next? I get the same warning when I say "Encrypt".

**Comment by Hyyperx0** [comment]
Sorry, I wrote it in the wrong place. I was going to write to your encryptor app.
